#pragma once

// 어셈블 관련 상수들
#define MAX_LABEL_NAME_LEN 32
#define MAX_LABEL_LEN 11
#define MAX_CMD_LEN 5
#define MAX_OPERANDS 5
#define INIT_LIST_CAPACITY 16

// 실행 관련 상수들
#define ERR_INVALID_ADDR 0x1
#define ERR_INVALID_PC 0x2
#define ERR_INVALID_BP 0x4
#define ERR_STACK_OVERFLOW 0x8
#define ERR_STACK_UNDERFLOW 0x10
#define ERR_CPU_STACK_OVERFLOW 0x20
#define ERR_CPU_STACK_UNDERFLOW 0x40

#define OPCODE_MAX 47

#define TOTAL_OPCODE_GROUPS 5

#define INIT_CPU_STACK_CAPACITY 100

#define INIT_MEMORY_SIZE 65536